name: Build & upload

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Install base dependencies
        run: |
          pacman -Syu --noconfirm archlinux-keyring
          pacman -Syu --noconfirm base-devel git cmake extra-cmake-modules ninja curl unzip doxygen kdoctools qt6-doc qt6-tools qt6-virtualkeyboard qt6-multimedia qt6-5compat qt6-wayland qt6-quick3d plasma-wayland-protocols plasma5support kvantum sddm sddm-kcm ksvg plasma-activities libplasma kwin

      - name: Create build user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fix permissions
        run: chown -R builder:builder .

        # Gotta install this like this because its not in arch repos
      - name: dependencies not available on arch repos
        run: |
          sudo -u builder sh <<'EOF'
          set -e
          git clone https://aur.archlinux.org/ttf-segoe-ui-variable.git
          cd ttf-segoe-ui-variable
          makepkg -s
          EOF
          cd ttf-segoe-ui-variable
          pacman -U *.pkg.tar.zst --noconfirm

      - name: Build
        run: |
          sudo -u builder sh <<'EOF'
          set -e
          cd aur

          #cd libplasma-aerothemeplasma
          #makepkg -s --skipinteg --skipchecksums --skippgpcheck
          #cd ..

          cd plasma6-aerothemeplasma-smod-git
          makepkg -s --skipinteg --skipchecksums --skippgpcheck
          EOF
          cd aur/plasma6-aerothemeplasma-smod-git
          pacman -U *.pkg.tar.zst --noconfirm
          sudo -u builder sh <<'EOF'
          cd aur
          cd plasma6-aerothemeplasma-git
          makepkg -s --skipinteg --skipchecksums --skippgpcheck
          EOF

      - name: Upload artifact/s
        uses: actions/upload-artifact@v4
        with:
          name: DLL
          path: |
            aur/*.pkg.tar.zst
