name: Build & upload

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Install base dependencies
        run: |
          pacman -Syu --noconfirm archlinux-keyring
          pacman -Syu --noconfirm base-devel git cmake extra-cmake-modules ninja curl unzip qt6-virtualkeyboard qt6-multimedia qt6-5compat qt6-wayland plasma-wayland-protocols plasma5support kvantum sddm sddm-kcm ksvg plasma-activities

      - name: Create build user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fix permissions
        run: chown -R builder:builder .

      - name: Build
        run: |
          sudo -u builder sh <<'EOF'
          set -e
          cd aur
          cd libplasma-aerothemeplasma
          makepkg -s
          cd ..
          cd plasma6-aerothemeplasma-git
          makepkg -s
          cd ..
          cd plasma6-aerothemeplasma-smod-git
          makepkg -s
          EOF

      - name: Upload artifact/s
        uses: actions/upload-artifact@v4
        with:
          name: DLL
          path: |
            aur/*.pkg.tar.zst
